// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для заказа
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	ProductSKU    int64                  `protobuf:"varint,3,opt,name=ProductSKU,proto3" json:"ProductSKU,omitempty"`
	OrderID       int64                  `protobuf:"varint,4,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Order) GetProductSKU() int64 {
	if x != nil {
		return x.ProductSKU
	}
	return 0
}

func (x *Order) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// // Сообщение для продукта в заказе
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Cnt           int64                  `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *Product) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OrderWithProduct struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Order             *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Product           *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Available         bool                   `protobuf:"varint,3,opt,name=Available,proto3" json:"Available,omitempty"`
	BalanceSufficient bool                   `protobuf:"varint,4,opt,name=balanceSufficient,proto3" json:"balanceSufficient,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderWithProduct) Reset() {
	*x = OrderWithProduct{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderWithProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderWithProduct) ProtoMessage() {}

func (x *OrderWithProduct) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderWithProduct.ProtoReflect.Descriptor instead.
func (*OrderWithProduct) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OrderWithProduct) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderWithProduct) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *OrderWithProduct) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *OrderWithProduct) GetBalanceSufficient() bool {
	if x != nil {
		return x.BalanceSufficient
	}
	return false
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x06protos\"\xa7\x01\n" +
	"\x05Order\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tTimestamp\x18\x02 \x01(\x03R\tTimestamp\x12\x1e\n" +
	"\n" +
	"ProductSKU\x18\x03 \x01(\x03R\n" +
	"ProductSKU\x12\x18\n" +
	"\aOrderID\x18\x04 \x01(\x03R\aOrderID\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"o\n" +
	"\aProduct\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x03R\x03sku\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x10\n" +
	"\x03cnt\x18\x03 \x01(\x03R\x03cnt\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xae\x01\n" +
	"\x10OrderWithProduct\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.protos.OrderR\x05order\x12)\n" +
	"\aproduct\x18\x02 \x01(\v2\x0f.protos.ProductR\aproduct\x12\x1c\n" +
	"\tAvailable\x18\x03 \x01(\bR\tAvailable\x12,\n" +
	"\x11balanceSufficient\x18\x04 \x01(\bR\x11balanceSufficientB\x1dZ\x1border_service/protos;protosb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messages_proto_goTypes = []any{
	(*Order)(nil),            // 0: protos.Order
	(*Product)(nil),          // 1: protos.Product
	(*OrderWithProduct)(nil), // 2: protos.OrderWithProduct
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: protos.OrderWithProduct.order:type_name -> protos.Order
	1, // 1: protos.OrderWithProduct.product:type_name -> protos.Product
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
