// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: messages.proto

package protos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для заказа
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	ProductSKU    int64                  `protobuf:"varint,3,opt,name=ProductSKU,proto3" json:"ProductSKU,omitempty"`
	OrderID       int64                  `protobuf:"varint,4,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Order) GetProductSKU() int64 {
	if x != nil {
		return x.ProductSKU
	}
	return 0
}

func (x *Order) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Сообщение для продукта в заказе
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Cnt           int64                  `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *Product) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OrderWithProduct struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Order             *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Product           *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Available         bool                   `protobuf:"varint,3,opt,name=Available,proto3" json:"Available,omitempty"`
	BalanceSufficient bool                   `protobuf:"varint,4,opt,name=balanceSufficient,proto3" json:"balanceSufficient,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderWithProduct) Reset() {
	*x = OrderWithProduct{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderWithProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderWithProduct) ProtoMessage() {}

func (x *OrderWithProduct) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderWithProduct.ProtoReflect.Descriptor instead.
func (*OrderWithProduct) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OrderWithProduct) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderWithProduct) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *OrderWithProduct) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *OrderWithProduct) GetBalanceSufficient() bool {
	if x != nil {
		return x.BalanceSufficient
	}
	return false
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *OrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersRequest) Reset() {
	*x = GetAllOrdersRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersRequest) ProtoMessage() {}

func (x *GetAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

type GetAllOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersResponse) Reset() {
	*x = GetAllOrdersResponse{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersResponse) ProtoMessage() {}

func (x *GetAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrdersByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserRequest) Reset() {
	*x = GetOrdersByUserRequest{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserRequest) ProtoMessage() {}

func (x *GetOrdersByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrdersByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserResponse) Reset() {
	*x = GetOrdersByUserResponse{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserResponse) ProtoMessage() {}

func (x *GetOrdersByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrdersByUserResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x06protos\x1a\x1cgoogle/api/annotations.proto\"\xa7\x01\n" +
	"\x05Order\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tTimestamp\x18\x02 \x01(\x03R\tTimestamp\x12\x1e\n" +
	"\n" +
	"ProductSKU\x18\x03 \x01(\x03R\n" +
	"ProductSKU\x12\x18\n" +
	"\aOrderID\x18\x04 \x01(\x03R\aOrderID\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"o\n" +
	"\aProduct\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x03R\x03sku\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x10\n" +
	"\x03cnt\x18\x03 \x01(\x03R\x03cnt\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xae\x01\n" +
	"\x10OrderWithProduct\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.protos.OrderR\x05order\x12)\n" +
	"\aproduct\x18\x02 \x01(\v2\x0f.protos.ProductR\aproduct\x12\x1c\n" +
	"\tAvailable\x18\x03 \x01(\bR\tAvailable\x12,\n" +
	"\x11balanceSufficient\x18\x04 \x01(\bR\x11balanceSufficient\")\n" +
	"\fOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"4\n" +
	"\rOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.protos.OrderR\x05order\"\x15\n" +
	"\x13GetAllOrdersRequest\"=\n" +
	"\x14GetAllOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.protos.OrderR\x06orders\"1\n" +
	"\x16GetOrdersByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"@\n" +
	"\x17GetOrdersByUserResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.protos.OrderR\x06orders2\xfc\x02\n" +
	"\fOrderService\x12B\n" +
	"\vCreateOrder\x12\r.protos.Order\x1a\r.protos.Order\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12R\n" +
	"\bGetOrder\x12\x14.protos.OrderRequest\x1a\r.protos.Order\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/-get-order/{order_id}\x12]\n" +
	"\fGetAllOrders\x12\x1b.protos.GetAllOrdersRequest\x1a\x1c.protos.GetAllOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12u\n" +
	"\x0fGetOrdersByUser\x12\x1e.protos.GetOrdersByUserRequest\x1a\x1f.protos.GetOrdersByUserResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/orders/user/{user_id}B\x17Z\x15clients/protos;protosb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messages_proto_goTypes = []any{
	(*Order)(nil),                   // 0: protos.Order
	(*Product)(nil),                 // 1: protos.Product
	(*OrderWithProduct)(nil),        // 2: protos.OrderWithProduct
	(*OrderRequest)(nil),            // 3: protos.OrderRequest
	(*OrderResponse)(nil),           // 4: protos.OrderResponse
	(*GetAllOrdersRequest)(nil),     // 5: protos.GetAllOrdersRequest
	(*GetAllOrdersResponse)(nil),    // 6: protos.GetAllOrdersResponse
	(*GetOrdersByUserRequest)(nil),  // 7: protos.GetOrdersByUserRequest
	(*GetOrdersByUserResponse)(nil), // 8: protos.GetOrdersByUserResponse
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: protos.OrderWithProduct.order:type_name -> protos.Order
	1, // 1: protos.OrderWithProduct.product:type_name -> protos.Product
	0, // 2: protos.OrderResponse.order:type_name -> protos.Order
	0, // 3: protos.GetAllOrdersResponse.orders:type_name -> protos.Order
	0, // 4: protos.GetOrdersByUserResponse.orders:type_name -> protos.Order
	0, // 5: protos.OrderService.CreateOrder:input_type -> protos.Order
	3, // 6: protos.OrderService.GetOrder:input_type -> protos.OrderRequest
	5, // 7: protos.OrderService.GetAllOrders:input_type -> protos.GetAllOrdersRequest
	7, // 8: protos.OrderService.GetOrdersByUser:input_type -> protos.GetOrdersByUserRequest
	0, // 9: protos.OrderService.CreateOrder:output_type -> protos.Order
	0, // 10: protos.OrderService.GetOrder:output_type -> protos.Order
	6, // 11: protos.OrderService.GetAllOrders:output_type -> protos.GetAllOrdersResponse
	8, // 12: protos.OrderService.GetOrdersByUser:output_type -> protos.GetOrdersByUserResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
